export type ThemeName = "classic" | "light" | "dark" | "retro" | "modern" | "cyberpunk" | "sunset";

export type Palette = {
  text: string;
  tint: string;
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  destructive: string;
  destructiveForeground: string;
  border: string;
  input: string;
  editorBackground: string;
  editorGutter: string;
  success: string;
  radius: number;
  titleGradient: [string, string];
  chromeGradient: [string, string];
  highlight: string;
  fontWeightHeavy?: boolean;
};

export const themes: Record<ThemeName, Palette> = {
  classic: {
    text: "#1a2334",
    tint: "#3a78c4",
    background: "#dbe5f1",
    foreground: "#1a2334",
    card: "#dde7f3",
    cardForeground: "#1a2334",
    primary: "#3a78c4",
    primaryForeground: "#ffffff",
    secondary: "#c4d5ec",
    secondaryForeground: "#1a2334",
    muted: "#eef3fa",
    mutedForeground: "#4a5e7a",
    accent: "#2c5d9b",
    accentForeground: "#ffffff",
    destructive: "#a83232",
    destructiveForeground: "#ffffff",
    border: "#7a96bd",
    input: "#7a96bd",
    editorBackground: "#ffffff",
    editorGutter: "#eef3fa",
    success: "#1f6f3f",
    radius: 4,
    titleGradient: ["#5a8fcf", "#2c5d9b"],
    chromeGradient: ["#eef3fa", "#cad9ed"],
    highlight: "#ffffff",
  },
  light: {
    text: "#1a1a1a",
    tint: "#0a64a4",
    background: "#f5f5f7",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#0a64a4",
    primaryForeground: "#ffffff",
    secondary: "#e6e6e6",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#5a5a5a",
    accent: "#0a64a4",
    accentForeground: "#ffffff",
    destructive: "#a83232",
    destructiveForeground: "#ffffff",
    border: "#cfcfcf",
    input: "#cfcfcf",
    editorBackground: "#ffffff",
    editorGutter: "#f4f4f4",
    success: "#1f6f3f",
    radius: 6,
    titleGradient: ["#ffffff", "#f0f0f0"],
    chromeGradient: ["#fafafa", "#ececec"],
    highlight: "#ffffff",
  },
  dark: {
    text: "#e6e6e6",
    tint: "#7da0d4",
    background: "#1e1e1e",
    foreground: "#e6e6e6",
    card: "#2a2a2a",
    cardForeground: "#e6e6e6",
    primary: "#4ea3dc",
    primaryForeground: "#0a0a0a",
    secondary: "#3a3a3a",
    secondaryForeground: "#e6e6e6",
    muted: "#262626",
    mutedForeground: "#a8a8a8",
    accent: "#4ea3dc",
    accentForeground: "#0a0a0a",
    destructive: "#e07070",
    destructiveForeground: "#1a1a1a",
    border: "#3f3f46",
    input: "#3f3f46",
    editorBackground: "#1e1e1e",
    editorGutter: "#262626",
    success: "#7fbf7f",
    radius: 6,
    titleGradient: ["#3a3a3a", "#1a1a1a"],
    chromeGradient: ["#2e2e2e", "#1f1f1f"],
    highlight: "#3a3a3a",
  },
  retro: {
    text: "#000000",
    tint: "#000080",
    background: "#c0c0c0",
    foreground: "#000000",
    card: "#c0c0c0",
    cardForeground: "#000000",
    primary: "#000080",
    primaryForeground: "#ffffff",
    secondary: "#a8a8a8",
    secondaryForeground: "#000000",
    muted: "#d4d0c8",
    mutedForeground: "#404040",
    accent: "#000080",
    accentForeground: "#ffffff",
    destructive: "#800000",
    destructiveForeground: "#ffffff",
    border: "#808080",
    input: "#808080",
    editorBackground: "#ffffff",
    editorGutter: "#dcdcdc",
    success: "#005900",
    radius: 0,
    titleGradient: ["#000080", "#000080"],
    chromeGradient: ["#c0c0c0", "#c0c0c0"],
    highlight: "#ffffff",
    fontWeightHeavy: true,
  },
  modern: {
    text: "#0f172a",
    tint: "#6366f1",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#6366f1",
    primaryForeground: "#ffffff",
    secondary: "#eef2ff",
    secondaryForeground: "#4338ca",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#8b5cf6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    editorBackground: "#ffffff",
    editorGutter: "#f8fafc",
    success: "#10b981",
    radius: 12,
    titleGradient: ["#ffffff", "#f8fafc"],
    chromeGradient: ["#ffffff", "#f1f5f9"],
    highlight: "#ffffff",
  },
  sunset: {
    text: "#1a3a3a",
    tint: "#0fa896",
    background: "#e6fbf7",
    foreground: "#1a3a3a",
    card: "#c6f1ea",
    cardForeground: "#1a3a3a",
    primary: "#ff3d8a",
    primaryForeground: "#ffffff",
    secondary: "#a8e8df",
    secondaryForeground: "#0e3a36",
    muted: "#dff8f3",
    mutedForeground: "#0e6b62",
    accent: "#2ec4b6",
    accentForeground: "#ffffff",
    destructive: "#c0264e",
    destructiveForeground: "#ffffff",
    border: "#2ec4b6",
    input: "#2ec4b6",
    editorBackground: "#f4fffd",
    editorGutter: "#cdeee8",
    success: "#0fa896",
    radius: 8,
    titleGradient: ["#ff7a3d", "#ff3d8a"],
    chromeGradient: ["#a8e8df", "#ffd0bd"],
    highlight: "#2ec4b6",
  },
  cyberpunk: {
    text: "#f0f6ff",
    tint: "#ff2bd1",
    background: "#0b0820",
    foreground: "#f0f6ff",
    card: "#150f33",
    cardForeground: "#f0f6ff",
    primary: "#ff2bd1",
    primaryForeground: "#0b0820",
    secondary: "#1f1850",
    secondaryForeground: "#9af7ff",
    muted: "#161139",
    mutedForeground: "#9af7ff",
    accent: "#00f0ff",
    accentForeground: "#0b0820",
    destructive: "#ff5577",
    destructiveForeground: "#0b0820",
    border: "#ff2bd1",
    input: "#3a2b6e",
    editorBackground: "#070518",
    editorGutter: "#0e0a26",
    success: "#76ff7a",
    radius: 2,
    titleGradient: ["#ff2bd1", "#7b00ff"],
    chromeGradient: ["#1a1340", "#0e0a26"],
    highlight: "#00f0ff",
  },
};

const colors = {
  light: themes.classic,
  dark: themes.dark,
  radius: 4,
};

export default colors;
